build: ../main.c ../GeneralFunctions.c ../SingleMode.c ../Play.c
	gcc ../main.c ../GeneralFunctions.c ../SingleMode.c ../Play.c -o app.exe
	gcc ../main.c ../GeneralFunctions.c ../SingleMode.c ../Play.c -o app.out